name: 'Argument Counter' # 이 액션의 이름(필수)
description: 'Count # of arguments passed in' # 액션 설명(필수)
inputs: # 액션 입력값 (선택)
  arguments-to-count: # input id
    description: 'arguments to count'
    required: true
    default: ''
outputs: # 액션 출력값(선택)
  arg-count:
    description: "Count of arguments passed in"
runs: # 액션 실제 실행(step으로 구분)
  using: "docker" # 액션 타입: 도커 액션
  image: 'Dockerfile' # 사용할 도커이미지(이 디렉토리의 Dockerfile로 항상 빌드)
  # 만약 빌드된 이미지를 사용할 경우 아래와 같이 진행한다.
  # 먼저 빌드 및 도커 허브 푸시: (docker build . -t openLeeWorld/arg-count-action:1.0.0), openLeeWorld 레지스트리에 푸시
  # image: 'docker://openLeeWorld/arg-count-action:1.0.0'
  args: # 해당 이미지에서 나온 프로세스에 들어갈 입력(인수 개수)
    - ${{ inputs.arguments-to-count }}

